Repository beyondessential/tupaia, pull requests merged in 2021-05, with the labels that each got.

#1522 885 Remove Mugil facility from STRIVE
  packages/database/README.md
  packages/database/src/migrations/20210420001619-RemoveMugilFromStrive-modifies-data.js
  packages/web-config-server/src/apiV1/dataBuilders/helpers/groupEvents.js
Labels: Team: Solutions

#2554 Release v2021-19.0 (Due 14/05/2021)
  packages/admin-panel/src/pages/StrivePage.js
  packages/admin-panel/src/pages/resources/QuestionsPage.js
  packages/admin-panel/src/widgets/InputField.js
  packages/admin-panel/src/widgets/JsonEditor.js
  packages/database/src/migrations/20210413033910-UpdateSTRIVEK13MapOverlay-modifies-data.js
  packages/database/src/migrations/20210422030246-CreateUnknownEntitiesForSamoa-modifies-data.js
  packages/database/src/migrations/20210505101731-AddSamoaCovidPercentageDashboards-modifies-data.js
  packages/database/src/migrations/20210506052033-AddSamoaCovidPercentageVaccinatedMeasures-modifies-data.js
  packages/database/src/migrations/20210507014219-PutWaiviviaToTheRightPlace-modifies-data.js
  packages/devops/scripts/lambda/createOrRestoreDeployment.py
  packages/devops/scripts/lambda/deleteDeployment.py
  packages/lesmis/.env.example
  packages/lesmis/src/components/ChartTable.js
  packages/lesmis/src/components/DashboardReportModal.js
  packages/lesmis/src/components/EntityPolygonLink.js
  packages/lesmis/src/components/EntityVitalsItem.js
  packages/lesmis/src/components/FullScreenDialog.js
  packages/lesmis/src/components/MiniMap.js
  packages/lesmis/src/components/NavBar.js
  packages/lesmis/src/components/Report.js
  packages/lesmis/src/components/Tabs.js
  packages/lesmis/src/components/index.js
  packages/lesmis/src/constants/constants.js
  packages/lesmis/src/views/DashboardReportTabView.js
  packages/lesmis/src/views/DashboardView.js
  packages/lesmis/src/views/MapView.js
  packages/meditrak-server/src/routes/importStriveLabResults/surveys.json
  packages/ui-components/src/components/Chart/Chart.js
  packages/ui-components/src/components/Chart/Table.js
  packages/ui-components/src/components/Map/EntityPolygon.js
  packages/ui-components/src/components/Map/Markers/IconMarker.js
  packages/ui-components/src/components/Map/Markers/markerIcons.js
  packages/ui-components/src/components/Map/PolygonLayer.js
  packages/ui-components/src/components/Map/index.js
  packages/ui-components/src/components/Table/DataFetchingTable.js
  packages/ui-components/src/components/Table/index.js
  packages/ui-components/stories/tables/dataFetchingTable.stories.js
  packages/web-config-server/src/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.js
  packages/web-config-server/src/tests/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.test.js
  packages/web-frontend/src/components/View/MatrixWrapper/MatrixWrapper.js
  packages/web-frontend/src/components/View/MatrixWrapper/components/Matrix.js
  packages/web-frontend/src/components/View/MatrixWrapper/components/Row.js
  packages/web-frontend/src/components/View/utils.js
  packages/web-frontend/src/images/matrix-placeholder-dot-only.png
  packages/web-frontend/src/images/matrix-placeholder-mix.png
  packages/web-frontend/src/images/matrix-placeholder-text-only.png
  packages/web-frontend/src/images/matrix-placeholder.png
  packages/web-frontend/src/screens/LoadingScreen/index.js
  packages/web-frontend/src/screens/desktop/RootScreen/index.js
  packages/web-frontend/src/screens/mobile/RootScreen/index.js
Labels: release

#2612 [Hot fix] Prevent multiple concurrent analytics refreshes
  packages/database/src/analytics/AnalyticsRefresher.js
  packages/database/src/tests/analytics/AnalyticsRefresher.test.js
Labels: ready for test
